# Generated by Django 4.2.4 on 2023-08-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
