# Generated by Django 4.2.4 on 2023-08-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_app', '0002_usage_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='accumulatedusage',
            name='price_in_dollars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
