# Generated by Django 4.2.4 on 2023-08-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_app', '0003_accumulatedusage_price_in_dollars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accumulatedusage',
            name='accumulated_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accumulatedusage',
            name='price_in_dollars',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
